### ISSUE TITLE
Can you provide a file structure for the HM3D dataset?

### ISSUE THREAD

**Issue by can922** [LYX0501/InstructNav#12]
Dear Author,

Thank you for your excellent work!

I encountered the following issue when running the project. I also referred to the official semantic test example of HM3D, and the result showed no issues. The error message is:

**QaLdnwvtxbs.basis.scn exists but failed to load.**

However, the file does not exist in the current directory. I suspect that the problem might be caused by an incorrect file structure. Could you provide a file structure for the HM3D dataset?

Currently, my mini file structure and the error message can be found in the log file. Thank you!
```
[16:10:19:241088]:[Error]:[Scene] SemanticScene.cpp(137)::loadSemanticSceneDescriptor : **SSD Load Failure!** File with SemanticAttributes-provided name `**/home/can/dataset/scenes/hm3d_v0.2/val/00829-QaLdnwvtxbs/QaLdnwvtxbs.basis.scn` exists but failed to load.**
Traceback (most recent call last):
  File "/home/can/InstructNav/objnav_benchmark.py", line 39, in <module>
    habitat_agent.reset()
  File "/home/can/InstructNav/objnav_agent.py", line 50, in reset
    self.obs = self.env.reset()
  File "/home/can/habitat-lab/habitat-lab/habitat/core/env.py", line 264, in reset
    self._task.measurements.reset_measures(
  File "/home/can/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 166, in reset_measures
    measure.reset_metric(*args, **kwargs)
  File "/home/can/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 858, in reset_metric
    self._draw_goals_aabb(episode)
  File "/home/can/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 771, in _draw_goals_aabb
    sem_scene.objects[object_id].id.split("_")[-1]
IndexError: list index out of range
```
 **The sem_scene.objects list has a length of 0, which leads to the error above.**
[log.txt](https://github.com/user-attachments/files/17644206/log.txt)

**Comment by Lazy-boy193** [comment]
> Dear Author,  亲爱的作家，
> 
> Thank you for your excellent work!感谢您的出色工作！
> 
> I encountered the following issue when running the project. I also referred to the official semantic test example of HM3D, and the result showed no issues. The error message is:运行项目时，我遇到了以下问题。我还提到了HM3D的官方语义测试示例，结果没有任何问题。错误消息是：
> 
> **QaLdnwvtxbs.basis.scn exists but failed to load.qaldnwvtxbs.basis.scn存在但无法加载。**
> 
> However, the file does not exist in the current directory. I suspect that the problem might be caused by an incorrect file structure. Could you provide a file structure for the HM3D dataset?但是，该文件在当前目录中不存在。我怀疑问题可能是由不正确的文件结构引起的。您能为HM3D数据集提供文件结构吗？
> 
> Currently, my mini file structure and the error message can be found in the log file. Thank you!当前，我的迷你文件结构和错误消息可以在日志文件中找到。谢谢你！
> 
> ```
> [16:10:19:241088]:[Error]:[Scene] SemanticScene.cpp(137)::loadSemanticSceneDescriptor : **SSD Load Failure!** File with SemanticAttributes-provided name `**/home/can/dataset/scenes/hm3d_v0.2/val/00829-QaLdnwvtxbs/QaLdnwvtxbs.basis.scn` exists but failed to load.**
> Traceback (most recent call last):
>   File "/home/can/InstructNav/objnav_benchmark.py", line 39, in <module>
>     habitat_agent.reset()
>   File "/home/can/InstructNav/objnav_agent.py", line 50, in reset
>     self.obs = self.env.reset()
>   File "/home/can/habitat-lab/habitat-lab/habitat/core/env.py", line 264, in reset
>     self._task.measurements.reset_measures(
>   File "/home/can/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 166, in reset_measures
>     measure.reset_metric(*args, **kwargs)
>   File "/home/can/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 858, in reset_metric
>     self._draw_goals_aabb(episode)
>   File "/home/can/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 771, in _draw_goals_aabb
>     sem_scene.objects[object_id].id.split("_")[-1]
> IndexError: list index out of range
> ```
> 
> **The sem_scene.objects list has a length of 0, which leads to the error above.SEM_SCENE.Objects列表的长度为0，这导致上面的错误。** [log.txt](https://github.com/user-attachments/files/17644206/log.txt)

Me too, I want to know the file directory structure of the HM3D dataset. Have you solved it?

**Comment by LYX0501** [comment]
Please try to set “draw_goal_aabbs=False” at https://github.com/LYX0501/InstructNav/blob/e58a5aac51cdb1c1ea4794ded0138e78f24de70f/config_utils.py#L30
