### ISSUE TITLE
Is the python version used in this project 3.9? 

### ISSUE THREAD

**Issue by ZhaoCancanCN** [LYX0501/InstructNav#9]
Thanks for your interesting work, I found a version conflict when installing python packages based on the requirement.txt you provided.  I first installed the packages required by requirement.txt and then installed the habitat related packages , and the following package incompatibility problem occurred. Can you elaborate on the installation sequence? Thank you very much!

![image](https://github.com/user-attachments/assets/54cb4eb2-1352-4ff0-bfd4-7d5eca8c3277)

**Comment by ZhaoCancanCN** [comment]
And I encountered a package conflict issue: after installing torch==2.2.2+cu121 and torchvision==0.17.2+cu121, adding xformers==0.0.28.post1 causes the torch version to automatically change to torch==2.4.1. Have you experienced a similar issue? Thank you.

**Comment by LYX0501** [comment]
Sorry, I haven't met such an issue. I am glad to provide one of our environment "python 3.9.19 with torch 2.1.2+cu118, torchvision 0.16.2+cu118, habitat-lab 0.3.1, habitat_sim 0.3.1" for you to have a reference.

**Comment by ZhaoCancanCN** [comment]
ok! Thank you for your reply.

**Comment by githubLeoliu** [comment]
> Sorry, I haven't met such an issue. I am glad to provide one of our environment "python 3.9.19 with torch 2.1.2+cu118, torchvision 0.16.2+cu118, habitat-lab 0.3.1, habitat_sim 0.3.1" for you to have a reference.

Can you also provide opencv and numpy version? I install these packages same as requirements.txt. But it seems like the opencv version and numpy version does not match with habitat.

Below is my conda env package version:
`(instruct-nav) leo@leo-System-Product-Name:~/Desktop/VLN/InstructNav$ conda list | grep cv
opencv-python             4.4.0.46                 pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
(instruct-nav) leo@leo-System-Product-Name:~/Desktop/VLN/InstructNav$ conda list | grep numpy
numpy                     1.23.5                   pypi_0    pypi
numpy-base                2.0.1            py39hb5e798b_1  
numpy-quaternion          2023.0.3                 pypi_0    pypi
(instruct-nav) leo@leo-System-Product-Name:~/Desktop/VLN/InstructNav$ conda list | grep habitat
habitat-lab               0.3.1                     dev_0    <develop>
habitat-sim               0.3.1                    pypi_0    pypi
(instruct-nav) leo@leo-System-Product-Name:~/Desktop/VLN/InstructNav$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
pytorch-cuda              11.8                 h7e8668a_6    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.4.1                    pypi_0    pypi
torchaudio                2.1.2                py39_cu118    pytorch
torchvision               0.16.2               py39_cu118    pytorch
`

The following the the error obtained from import habitat
`(instruct-nav) leo@leo-System-Product-Name:~/Desktop/VLN/InstructNav$ python objnav_benchmark.py 
Traceback (most recent call last):
  File "/home/leo/Desktop/VLN/InstructNav/objnav_benchmark.py", line 1, in <module>
    import habitat
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/__init__.py", line 9, in <module>
    from habitat.core.benchmark import Benchmark
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 20, in <module>
    from habitat.core.env import Env
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/core/env.py", line 30, in <module>
    from habitat.datasets import make_dataset
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/datasets/__init__.py", line 7, in <module>
    from habitat.datasets.registration import make_dataset  # noqa: F401 .
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/datasets/registration.py", line 25, in <module>
    _try_register_objectnavdatasetv1()
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/datasets/object_nav/__init__.py", line 20, in _try_register_objectnavdatasetv1
    from habitat.datasets.object_nav.object_nav_dataset import (  # noqa: F401
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/datasets/object_nav/object_nav_dataset.py", line 14, in <module>
    from habitat.datasets.pointnav.pointnav_dataset import (
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 16, in <module>
    from habitat.tasks.nav.nav import (
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/tasks/nav/nav.py", line 42, in <module>
    from habitat.utils.visualizations import fog_of_war, maps
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/utils/visualizations/__init__.py", line 7, in <module>
    from habitat.utils.visualizations import maps, utils
  File "/home/leo/Desktop/VLN/InstructNav/habitat-sim/habitat-lab/habitat-lab/habitat/utils/visualizations/maps.py", line 44, in <module>
    TOP_DOWN_MAP_COLORS[10:] = cv2.applyColorMap(
TypeError: Expected Ptr<cv::UMat> for argument 'src'
`
